# Generated by Django 5.2.4 on 2025-11-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
