# Generated by Django 5.2.4 on 2025-11-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
